### ISSUE TITLE
Rename Github repo to foresight-docs

### ISSUE THREAD

**Issue by jacobcsmith** [saic-oss/cloudscend-foresight-docs#20]
## Describe the Feature

Rename this repo from sage-docs to foresight-docs.

## Use Case

The product name was changed from Sage to CloudScend Foresight so we are working on removing all references to the old name in the product and in the documentation.

## Describe Ideal Solution

The Github repo is renamed to foresight-docs. 

## Alternatives Considered

We considered leaving the repo name as-is but felt it was best to change at this point since the product has not officially launched. 

We also considered renaming the repo to cloudscend-foresight-docs. This could work as well but we felt it was too long.

**Comment by RothAndrew** [comment]
No problem. I assume you want this done for the sage-charts repo as well?

**Comment by RothAndrew** [comment]
> We also considered renaming the repo to cloudscend-foresight-docs. This could work as well but we felt it was too long.

I wouldn't consider that overly long. It may be beneficial in case there are other cloudscend products that end up here as well. I'm fine with either option.

**Comment by jacobcsmith** [comment]
I'll confirm with Roger on how he'd like to proceed.

**Comment by jacobcsmith** [comment]
Roger would like to use cloudscend-foresight-docs
